name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - labeled

env:
  CHART_DIR: "helm/alfresco-process-infrastructure"
  # TODO: create dedicated cluster?
  TEST_CLUSTER_NAME: activiti
  HELM_REPO_BASE_URL: https://kubernetes-charts.alfresco.com
  HELM_REPO: Alfresco/charts
  HELM_REPO_BRANCH: master
  HELM_REPO_SUBFOLDER: incubator

jobs:

  check-bot-build:
    name: Check dependabot build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Activiti/Activiti/.github/actions/check-ext-build@8.0.0-alpha.10

  pre-commit:
    needs: check-bot-build
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v3.7.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-kubepug@v3.7.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v3.7.0
      - uses: bridgecrewio/checkov-action@v12.1839.0
        with:
          framework: kubernetes

  validate:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: Alfresco/alfresco-build-tools/.github/actions/validate-maven-versions@v3.7.0
        with:
          maven-username: ${{ secrets.NEXUS_USERNAME }}
          maven-password: ${{ secrets.NEXUS_PASSWORD }}

  build:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - validate
    env:
      TARGET_CHARTS_PATH: charts
    steps:
      - uses: actions/checkout@v3

      - name: Define test namespace
        id: define-namespace
        env:
          RUN_ID: ${{ github.run_id }}
        # hardcode repo name as helm release name is limited to 53 chars
        run: echo "name=gh-process-infrastructure-deployment-$RUN_ID" >> $GITHUB_OUTPUT

      - name: Build
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-build-chart@v3.7.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - name: Execute dry run
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-integration-tests@v3.7.0
        with:
          chart-dir: ${{ env.CHART_DIR }}
          test-rancher-url: ${{ secrets.RANCHER2_URL }}
          test-rancher-access-key: ${{ secrets.RANCHER2_ACCESS_KEY }}
          test-rancher-secret-key: ${{ secrets.RANCHER2_SECRET_KEY }}
          test-cluster-name: ${{ env.TEST_CLUSTER_NAME }}
          test-namespace: ${{ steps.define-namespace.outputs.name }}

      - name: Package Helm Chart
        id: package-helm-chart
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-package-chart@v3.7.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

  release:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.calculate-next-internal-version.outputs.next-prerelease }}
    steps:
      - uses: actions/checkout@v3

      - name: Parse next release
        id: helm-parse-next-release
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-parse-next-release@v3.7.0
        with:
          chart-dir: ${{ env.CHART_DIR }}

      - id: calculate-next-internal-version
        name: Calculate next internal release
        uses: Alfresco/alfresco-build-tools/.github/actions/calculate-next-internal-version@v3.7.0
        with:
          next-version: ${{ steps.helm-parse-next-release.outputs.next-release }}

      - id: helm-release-and-publish
        name: Release and publish helm chart
        uses: Alfresco/alfresco-build-tools/.github/actions/helm-release-and-publish@v3.7.0
        with:
          version: ${{ steps.calculate-next-internal-version.outputs.next-prerelease }}
          chart-dir: ${{ env.CHART_DIR }}
          helm-repository: ${{ env.HELM_REPO }}
          helm-repository-branch: ${{ env.HELM_REPO_BRANCH }}
          helm-repository-subfolder: ${{ env.HELM_REPO_SUBFOLDER }}
          helm-repository-base-url: ${{ env.HELM_REPO_BASE_URL }}
          helm-repository-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          do-push: ${{ github.event_name == 'push' }}

  promote:
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'push'
    env:
      VERSION: ${{ needs.release.outputs.version }}
      DEVELOPMENT_BRANCH: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - id: activiti-cloud-common-chart-version
        working-directory: helm/alfresco-process-infrastructure
        run: |
          RESULT=`yq '.dependencies | map(select(.name == "common")) | .[0].version' Chart.yaml`
          echo ${RESULT}
          echo "result=${RESULT}" >> $GITHUB_OUTPUT
      - id: alfresco-deployment-service-version
        working-directory: helm/alfresco-process-infrastructure
        run: |
          RESULT=`yq '.alfresco-deployment-service.image.tag' values.yaml`
          echo ${RESULT}
          echo "result=${RESULT}" >> $GITHUB_OUTPUT
      - uses: Alfresco/alfresco-build-tools/.github/actions/jx-updatebot-pr@v3.7.0
        env:
          ACTIVITI_CLOUD_COMMON_CHART_VERSION: ${{ steps.activiti-cloud-common-chart-version.outputs.result }}
          ALFRESCO_DEPLOYMENT_SERVICE_VERSION: ${{ steps.alfresco-deployment-service-version.outputs.result }}
        with:
          version: ${{ env.VERSION }}
          auto-merge: 'true'
          labels: ${{ env.DEVELOPMENT_BRANCH }}
          base-branch-name: ${{ env.DEVELOPMENT_BRANCH }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          git-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          git-author-name: ${{ secrets.BOT_GITHUB_USERNAME }}

  notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - release
      - promote
    if: always() && failure() && github.event_name == 'push'
    steps:
      - name: Slack Notification
        uses: Alfresco/alfresco-build-tools/.github/actions/send-slack-notification@v3.7.0
        with:
          channel-id: 'eng-hxp-studio-be-gh-notifs'
          token: ${{ secrets.SLACK_NOTIFICATION_BOT_TOKEN }}
